FROM ubuntu:22.04@sha256:b8b6ee6aa931ecd9d0d952abc34dc0e5f7c6a30c6bb71b079fe399fde0329c02 AS build
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends gcc make bison flex bzip2 perl libc6-dev ca-certificates && rm -rf /var/lib/apt/lists/*
WORKDIR /build
COPY postgresql-18.6.tar.bz2 .
RUN echo '555610c24d53e4316da5b7d3fc25c279d96856d5e0e23ee308c328c5fa881d9f  postgresql-18.6.tar.bz2' | sha256sum -c - && tar -xf postgresql-18.6.tar.bz2
WORKDIR /build/postgresql-18.6
RUN ./configure --prefix=/opt/tacticus-postgres --without-readline --without-zlib --without-icu --disable-rpath && make -j4 && make DESTDIR=/package install-strip && cp COPYRIGHT /package/opt/tacticus-postgres/COPYRIGHT
FROM scratch AS package
COPY --from=build /package/opt/tacticus-postgres /postgres
