import { describe, expect, it, vi } from 'vitest'

import { handleDuplicateDisplayNames } from '@/app/lib/sync/transformers'
import { disambiguateDuplicateDisplayNames } from '@/supabase/functions/_shared/display-name-dedup'

// The dedup suffix is a load-bearing join key generated by two copies (app and Deno edge);
// on failure fix the drift, not the fixture.

const GUILD_CODE = 'EOT'

type FixtureMember = {
  userId: string
  displayName: string
  role: string
}

function buildFixture(): FixtureMember[] {
  const members: FixtureMember[] = [
    // Out of userId order to pin the userId sort as the tie-break.
    { userId: 'user-b', displayName: 'Alex', role: 'member' },
    { userId: 'user-a', displayName: 'Alex', role: 'officer' },
    { userId: 'user-c', displayName: 'Blair', role: 'member' },
    { userId: 'user-z', displayName: 'Zed', role: 'leader' },
    { userId: 'user-w2', displayName: ' Casey ', role: 'member' },
    { userId: 'user-w1', displayName: 'Casey', role: 'member' },
    { userId: 'user-w3', displayName: 'Casey\t', role: 'member' },
    { userId: 'user-empty', displayName: '', role: 'member' }
  ]

  for (let i = 11; i >= 1; i--) {
    members.push({
      userId: `dup-${String(i).padStart(3, '0')}`,
      displayName: 'Legion',
      role: 'member'
    })
  }

  return members
}

function normalize(
  members: Array<{
    userId: string
    displayName: string
    originalDisplayName?: string | null
    hasDuplicateName?: boolean
  }>
) {
  return members.map((member) => ({
    userId: member.userId,
    displayName: member.displayName,
    originalDisplayName: member.originalDisplayName ?? null,
    hasDuplicateName: member.hasDuplicateName === true
  }))
}

describe('display-name dedup suffix parity (app vs edge)', () => {
  it('produces identical output for the shared fixture in both runtimes', () => {
    const warn = vi.fn()

    const appResult = handleDuplicateDisplayNames(buildFixture(), GUILD_CODE)
    const edgeResult = disambiguateDuplicateDisplayNames(
      buildFixture(),
      GUILD_CODE,
      { warn }
    )

    expect(normalize(edgeResult)).toEqual(normalize(appResult))
    expect(warn).toHaveBeenCalledTimes(3)
  })

  it('pins the exact suffix format both copies must emit', () => {
    const appResult = handleDuplicateDisplayNames(buildFixture(), GUILD_CODE)
    const byUserId = new Map(appResult.map((m) => [m.userId, m.displayName]))

    expect(byUserId.get('user-a')).toBe('Alex (EOT_01)')
    expect(byUserId.get('user-b')).toBe('Alex (EOT_02)')
    expect(byUserId.get('user-w1')).toBe('Casey (EOT_01)')
    expect(byUserId.get('user-w2')).toBe('Casey (EOT_02)')
    expect(byUserId.get('user-w3')).toBe('Casey (EOT_03)')
    expect(byUserId.get('dup-001')).toBe('Legion (EOT_01)')
    expect(byUserId.get('dup-009')).toBe('Legion (EOT_09)')
    expect(byUserId.get('dup-010')).toBe('Legion (EOT_10)')
    expect(byUserId.get('dup-011')).toBe('Legion (EOT_11)')
    expect(byUserId.get('user-c')).toBe('Blair')
    expect(byUserId.get('user-empty')).toBe('')
  })

  it('treats inherited object keys as ordinary display names', () => {
    const members: FixtureMember[] = [
      { userId: 'reserved-1', displayName: '__proto__', role: 'member' },
      { userId: 'reserved-2', displayName: 'constructor', role: 'member' }
    ]
    const warn = vi.fn()

    const appResult = handleDuplicateDisplayNames(members, GUILD_CODE)
    const edgeResult = disambiguateDuplicateDisplayNames(members, GUILD_CODE, {
      warn
    })

    expect(normalize(edgeResult)).toEqual(normalize(appResult))
    expect(appResult.map((member) => member.displayName)).toEqual([
      '__proto__',
      'constructor'
    ])
    expect(warn).not.toHaveBeenCalled()
  })
})
