export const TIME_UNITS = {
  MILLISECOND: 1,
  SECOND: 1000,
  MINUTE: 60 * 1000,
  HOUR: 60 * 60 * 1000,
  DAY: 24 * 60 * 60 * 1000,
  WEEK: 7 * 24 * 60 * 60 * 1000
} as const

export const LIVE_STATS_CACHE_TTL = {
  INSTANT: 0,
  VERY_SHORT: 30 * TIME_UNITS.SECOND,
  SHORT: TIME_UNITS.MINUTE,
  MEDIUM_SHORT: 2 * TIME_UNITS.MINUTE,

  MEDIUM: 5 * TIME_UNITS.MINUTE,
  STANDARD: 10 * TIME_UNITS.MINUTE,
  EXTENDED: 15 * TIME_UNITS.MINUTE,
  LONG: 30 * TIME_UNITS.MINUTE,

  VERY_LONG: TIME_UNITS.HOUR,
  EXTRA_LONG: 6 * TIME_UNITS.HOUR,
  DAILY: TIME_UNITS.DAY,
  WEEKLY: TIME_UNITS.WEEK,

  GUILD_CONFIG: 30 * TIME_UNITS.MINUTE,
  SEASONS: 15 * TIME_UNITS.MINUTE,
  PLAYER_DATA: 5 * TIME_UNITS.MINUTE,
  BOSS_DATA: 10 * TIME_UNITS.MINUTE,
  SUMMARY_DATA: 3 * TIME_UNITS.MINUTE,
  TOKEN_DATA: 5 * TIME_UNITS.MINUTE,
  DEBUG_DATA: TIME_UNITS.MINUTE,
  STATIC_DATA: TIME_UNITS.DAY // hero mappings, etc.
} as const
